runtime: php72

handlers:
  # Serve a directory as a static resource.
  - url: /css
    static_dir: public/css
  - url: /js
      static_dir: public/js

# Put production environment variables here.
env_variables:
  # Applicaton key
  APP_KEY: base64:neD3pkZQV26sd9OxZ8cp3jyERMnrt0X5guevJzw65N4=
  # Storage path
  APP_STORAGE: /tmp
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: running-laravel-on-gcp
  DB_USERNAME: root
  DB_PASSWORD: secret
#  DB_SOCKET: "/cloudsql/running-laravel-on-gcp:asia-southeast1:running-laravel-on-gcp"
  FILESYSTEM_DRIVER: gcs
  FILESYSTEM_CLOUD: gcs
  GOOGLE_CLOUD_PROJECT_ID: running-laravel-on-gcp
  GOOGLE_CLOUD_STORAGE_BUCKET: running-laravel-on-gcp.appspot.com
  GOOGLE_CLOUD_STORAGE_API_URI: https://storage.cloud.google.com/running-laravel-on-gcp

